---
## Tesseract
## configure vars in ../vars/main.yml

- name: get tesseract
  apt: pkg=tesseract-ocr

- name: Get english language files
  apt: pkg=tesseract-ocr-eng

- name: Get French language files
  apt: pkg=tesseract-ocr-fra
