islandora_mods:
    - islandora_openseadragon
    - php_lib 
    - objective_forms
    - islandora_solr 
    - islandora_solr_metadata 
    - islandora_solr_facet_pages 
    - islandora_solr_views
    - islandora_basic_collection 
    - islandora_pdf 
    - islandora_audio 
    - islandora_book 
    - islandora_compound_object 
    - islandora_disk_image
    - islandora_entities
    - islandora_entities_csv_import
    - islandora_basic_image
    - islandora_large_image
    - islandora_newspaper
    - islandora_video
    - islandora_web_archive
    - islandora_premis 
    - islandora_checksum
    - islandora_checksum_checker
    - islandora_book_batch
    - islandora_image_annotation
    - islandora_pathauto
    - islandora_pdfjs
    - islandora_videojs
    - islandora_jwplayer
    - xml_forms 
    - xml_form_builder
    - xml_schema_api
    - xml_form_elements
    - xml_form_api
    - jquery_update
    - zip_importer
    - islandora_basic_image
    - islandora_bibliography
    - islandora_compound_object
    - islandora_google_scholar
    - islandora_scholar_embargo
    - islandora_solr_config
    - citation_exporter
    - doi_importer
    - endnotexml_importer
    - pmid_importer
    - ris_importer
    - islandora_fits
    - islandora_ocr
    - islandora_oai
    - islandora_marcxml
    - islandora_simple_workflow
    - islandora_xacml_api
    - islandora_xacml_editor
    - xmlsitemap
    - islandora_xmlsitemap
    - colorbox
    - islandora_internet_archive_bookreader
    - islandora_bagit
    - islandora_batch_report
    - islandora_usage_stats
    - islandora_form_fieldpanel
    - islandora_altmetrics
    - islandora_populator
	
third_party_mods:
    - date
    - datepicker
    - xmlsitemap
    - features
