---
- name: Cloning islandora modules
  git: clone=yes repo="https://github.com/islandora/{{item}}.git" dest="{{modules_dir}}/{{item}}" version=7.x update=no
  with_items:
    - islandora
    - islandora_bagit
    - islandora_batch
    - islandora_book_batch
    - islandora_bookmark
    - islandora_checksum
    - islandora_checksum_checker
    - islandora_fits
    - islandora_image_annotation
    - islandora_importer
    - islandora_internet_archive_bookreader
    - islandora_jwplayer
    - islandora_marcxml
    - islandora_oai
    - islandora_ocr
    - islandora_openseadragon
    - islandora_paged_content
    - islandora_pathauto
    - islandora_pdfjs
    - islandora_premis
    - islandora_scholar
    - islandora_simple_workflow
    - islandora_solr_facet_pages
    - islandora_solr_metadata
    - islandora_solr_search
    - islandora_solr_views
    - islandora_solution_pack_audio
    - islandora_solution_pack_book
    - islandora_solution_pack_collection
    - islandora_solution_pack_compound
    - islandora_solution_pack_disk_image
    - islandora_solution_pack_entities
    - islandora_solution_pack_image
    - islandora_solution_pack_large_image
    - islandora_solution_pack_newspaper
    - islandora_solution_pack_pdf
    - islandora_solution_pack_video
    - islandora_solution_pack_web_archive
    - islandora_videojs
    - islandora_xacml_editor
    - islandora_xml_forms
    - islandora_xmlsitemap
    - objective_forms
    - php_lib
    - islandora_populator


- name: Set git config filemode off
  shell: git config core.filemode false
  args:
    chdir: "{{modules_dir}}/{{item}}"
  with_items:
    - islandora
    - islandora_bagit
    - islandora_batch
    - islandora_book_batch
    - islandora_bookmark
    - islandora_checksum
    - islandora_checksum_checker
    - islandora_fits
    - islandora_image_annotation
    - islandora_importer
    - islandora_internet_archive_bookreader
    - islandora_jwplayer
    - islandora_marcxml
    - islandora_oai
    - islandora_ocr
    - islandora_openseadragon
    - islandora_paged_content
    - islandora_pathauto
    - islandora_pdfjs
    - islandora_premis
    - islandora_scholar
    - islandora_simple_workflow
    - islandora_solr_facet_pages
    - islandora_solr_metadata
    - islandora_solr_search
    - islandora_solr_views
    - islandora_solution_pack_audio
    - islandora_solution_pack_book
    - islandora_solution_pack_collection
    - islandora_solution_pack_compound
    - islandora_solution_pack_disk_image
    - islandora_solution_pack_entities
    - islandora_solution_pack_image
    - islandora_solution_pack_large_image
    - islandora_solution_pack_newspaper
    - islandora_solution_pack_pdf
    - islandora_solution_pack_video
    - islandora_solution_pack_web_archive
    - islandora_videojs
    - islandora_xacml_editor
    - islandora_xml_forms
    - islandora_xmlsitemap
    - objective_forms
    - php_lib
    - islandora_populator